### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by timon-test** [pinkcubeecommerce/service-desk#1]
Testing workflow.

**Comment by timonschenzel** [comment]
Discussie over requirements..

**Comment by timonschenzel** [comment]
Dev workflow.. code schrijven.. pr..

**Comment by timonschenzel** [comment]
Code is klaar, internal review flow..

**Comment by timonschenzel** [comment]
End-user review..

**Comment by timonschenzel** [comment]
Done.

**Comment by timonschenzel** [comment]
@timon-test ??

**Comment by timon-test** [comment]
Reaction from mail..
________________________________
Van: Timon Schenzel <notifications@github.com>
Verzonden: donderdag 12 november 2020 16:47
Aan: pinkcubeecommerce/service-desk <service-desk@noreply.github.com>
CC: timon-test <tom11a@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [pinkcubeecommerce/service-desk] First issue (#1)


@timon-test<https://github.com/timon-test> ??
